[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/base16-shell"]
    type = "archive"
    url = "https://github.com/chriskempson/base16-shell/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".rbenv"]
    type = "archive"
    url = "https://github.com/rbenv/rbenv/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

["tools/zgen"]
    type = "archive"
    url = "https://github.com/tarjoilija/zgen/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

["tools/z"]
    type = "archive"
    url = "https://github.com/rupa/z/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"