[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "24h"

["tools/zgenom"]
    type = "archive"
    url = "https://github.com/jandamm/zgenom/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "24h"
    exclude = ["sources/**/*"]

["tools/z"]
    type = "archive"
    url = "https://github.com/rupa/z/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "24h"

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
