#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.5

yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config mouse_modifier               off
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# per-application rule
yabai -m rule --add app=".*" manage=off

yabai -m rule --add app="Slack" manage=on layer=above
yabai -m rule --add app="FaceTime" layer=above
yabai -m rule --add app="Google Chrome" manage=on
yabai -m rule --add app="kitty" manage=on
yabai -m rule --add app="Notion" manage=on
yabai -m rule --add app="Todoist" manage=on
yabai -m rule --add app="GoodNotes 5" manage=on
yabai -m rule --add app="Slack" layer=above
yabai -m rule --add app="zoom.us" layer=above

yabai -m rule --add title="^$" manage=off

yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-spaces-primary-jsx\"'"

echo "yabai configuration loaded.."
