#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Iosevka:Regular:10.0"
yabai -m config status_bar_icon_font         "SF Symbol:Regular:10.0"
yabai -m config status_bar_background_color  0xff000000
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9
yabai -m config status_bar_power_icon_strip  􀒘 􀛪
yabai -m config status_bar_space_icon        􀒱
yabai -m config status_bar_clock_icon        􀐫

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.5

yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xfff0134d
yabai -m config normal_window_border_color   0xff5b5656
yabai -m config insert_window_border_color   0xff192965

yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config mouse_modifier               off
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# per-application rule
yabai -m rule --add app="Finder" title=".*Copy.*" manage=off
yabai -m rule --add app="Finder" title=".*Move.*" manage=off
yabai -m rule --add app="Finder" title=".*Info.*" manage=off
yabai -m rule --add app="Finder" title=".*Connect.*" manage=off

yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="iTunes" manage=off
yabai -m rule --add app="Music" manage=off
yabai -m rule --add app="Pocket Casts" manage=off
yabai -m rule --add app="FaceTime" manage=off
yabai -m rule --add app="1Password" manage=off
yabai -m rule --add app="Dictionary" manage=off
yabai -m rule --add app="Home" manage=off
yabai -m rule --add app="The Unarchiver" manage=off
yabai -m rule --add app="Slack" manage=float layer=above

yabai -m rule --add app="NVIDIA GeForce NOW" manage=off

yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="System Preferences" manage=off

echo "yabai configuration loaded.."
