gui:
  scrollHeight: 8
  showRandomTip: false
  showIcons: true
  commandLogSize: 8
  showBottomLine: false
git:
  parseEmoji: true
keybinding:
  universal:
    quit: 'Q'
    return: 'q'
    quitWithoutChangingDirectory: ''
