#!/bin/sh

mkdir -p ~/local/bin

mkdir -p ~/tools

mkdir -p ~/.vim/tmp/undo
mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/swap

touch $HOME/.psqlrc.local

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fkLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
$EDITOR -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa

if [ ! -e $HOME/.config/base16-shell ]; then
    git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
fi

if [ ! -e $HOME/.tmuxifier ]; then
    git clone https://github.com/jimeh/tmuxifier.git $HOME/.tmuxifier
fi

if [ ! -e $HOME/tools/zgen ]; then
    git clone https://github.com/tarjoilija/zgen.git $HOME/tools/zgen
fi

if [ ! -e $HOME/tools/z ]; then
    git clone https://github.com/rupa/z.git $HOME/tools/z
    touch ~/.z
fi

if [ ! -e $HOME/tools/tmux-powerline ]; then
    git clone https://github.com/erikw/tmux-powerline.git $HOME/tools/tmux-powerline
fi

if [ ! -e $HOME/tools/tmux-mem-cpu-load ]; then
    git clone https://github.com/thewtex/tmux-mem-cpu-load.git $HOME/tools/tmux-mem-cpu-load
    cd $HOME/tools/tmux-mem-cpu-load
    # brew install cmake || sudo apt-get install cmake
    cmake .
    make -j4
    chmod +x tmux-mem-cpu-load
    ln -f -s $HOME/tools/tmux-mem-cpu-load/tmux-mem-cpu-load $HOME/local/bin
fi

if [ ! -e $HOME/tools/the_silver_searcher ]; then
    git clone https://github.com/ggreer/the_silver_searcher.git $HOME/tools/the_silver_searcher
    cd $HOME/tools/the_silver_searcher
    ./build.sh
    make
    ln -f -s $HOME/tools/the_silver_searcher/ag $HOME/local/bin
fi

if [ ! -e $HOME/tools/ctags ]; then
    cd /tmp
    wget http://prdownloads.sourceforge.net/ctags/ctags-5.8.tar.gz
    tar xfz ctags-5.8.tar.gz
    mv ctags-5.8 $HOME/tools/ctags
    cd $HOME/tools/ctags
    ./configure --prefix=$HOME/local
    make
    ln -f -s $HOME/tools/ctags/ctags $HOME/local/bin
fi

if [ ! -e $HOME/tools/tig ]; then
    cd /tmp
    wget http://jonas.nitro.dk/tig/releases/tig-2.1.tar.gz
    tar xfz tig-2.1.tar.gz
    mv tig-2.1 $HOME/tools/tig
    cd $HOME/tools/tig
    ./autogen.sh
    ./configure --prefix=$HOME/local
    make
    ln -f -s $HOME/tools/tig/src/tig $HOME/local/bin
fi

if [ ! -e $HOME/.nvimrc ]; then
    ln -f $HOME/.vimrc $HOME/.nvimrc
    ln -s $HOME/.vim $HOME/.nvim
fi
