#!/bin/sh

mkdir -p ~/local/bin

mkdir -p ~/tools

mkdir -p ~/.vim/tmp/undo
mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/swap

if [ ! -e $HOME/.tmuxifier ]; then
    git clone https://github.com/jimeh/tmuxifier.git $HOME/.tmuxifier
fi

if [ ! -e $HOME/tools/zgen ]; then
    git clone https://github.com/tarjoilija/zgen.git $HOME/tools/zgen
fi

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
vim -u $HOME/.vimrc.bundles +PluginInstall +PluginClean! +qa

if [ ! -e $HOME/tools/z ]; then
    git clone https://github.com/rupa/z.git $HOME/tools/z
    touch ~/.z
fi

if [ ! -e $HOME/tools/tmux-powerline ]; then
    git clone https://github.com/erikw/tmux-powerline.git $HOME/tools/tmux-powerline
fi

if [ ! -e $HOME/tools/tmux-mem-cpu-load ]; then
    git clone https://github.com/thewtex/tmux-mem-cpu-load.git $HOME/tools/tmux-mem-cpu-load
    cd $HOME/tools/tmux-mem-cpu-load
    brew install cmake || sudo apt-get install cmake
    cmake .
    make -j4
    chmod +x tmux-mem-cpu-load
    ln -f -s $HOME/tools/tmux-mem-cpu-load/tmux-mem-cpu-load $HOME/local/bin
fi
